### ISSUE TITLE
Playground: resizable panes

### ISSUE THREAD

**Issue by lieuwex** [tomsmeding/pastebin-haskell#19]
So you can change the ratio between code editor width and output pane width.

**Comment by hasufell** [comment]
@arjunkathuria

**Comment by arjunkathuria** [comment]
yea, don't worry about it lol, i'll get this.

Been meaning to use CSS Grids spec in a project, seems like the time has come

**Comment by tomsmeding** [comment]
I already did this in https://github.com/tomsmeding/pastebin-haskell/commit/f8a40b8ff4d7dfa88bf8e43d0a429bc77576a454 and forgot to close the issue :)
