### ISSUE TITLE
GLIBC error on GHC 9.4.2

### ISSUE THREAD

**Issue by Player-205** [tomsmeding/pastebin-haskell#22]
Current behavior:
```
Command exited with code 1.
GHC output

/home/tom/.ghcup/ghc/9.4.2/lib/ghc-9.4.2/bin/./ghc-9.4.2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/tom/.ghcup/ghc/9.4.2/lib/ghc-9.4.2/bin/../lib/x86_64-linux-ghc-9.4.2/libHSrts-1.0.2_thr-ghc9.4.2.so)
```

Expected behavior:
As for other ghc versions

Steps to reproduce:
1) Open https://play-haskell.tomsmeding.com/
2) Change GHC to 9.4.2
3) Click "run"

**Comment by tomsmeding** [comment]
Thank you for the precise and detailed reproduction steps. :)

I need to follow my own instructions, documented in [the readme that I wrote myself](https://github.com/tomsmeding/pastebin-haskell/tree/play/play-haskell-server#ghcup-target-platform). The problem has been fixed.

Thanks for reporting!
