### ISSUE TITLE
Download single file as single file (no tar)

### ISSUE THREAD

**Issue by tomsmeding** [tomsmeding/pastebin-haskell#24]
Suggested by [cheater](https://ircbrowse.tomsmeding.com/day/lchaskell/2022/11/07?id=764009#trid764009)

**Comment by cheater** [comment]
i had no idea you could have multiple files. if multiple files give you tar.gz and one file gives you just the file, then it's inconsistent, but maybe this inconsistency is fine.

or have a link under every file to "download this file" and a link at the bottom or top to "download all files (tar.gz)"

**Comment by tomsmeding** [comment]
As further discussed on IRC this would introduce inconsistency where it is unnecessary, because to download a single file one can simply click `raw` and save the resulting file.
