### ISSUE TITLE
Make it pretty by adding nice CSS

### ISSUE THREAD

**Issue by hyiltiz** [tomsmeding/pastebin-haskell#5]
Ideally via just CSS without js hooks, bells and whistles...

**Comment by tomsmeding** [comment]
This is extremely necessary at this point because I haven't really made any effort to make it nice, and it shows.

Please someone with some design props, make it nicer than it is.

**Comment by hyiltiz** [comment]
I've found there are a few popular js-free CSS frameworks out there:
https://purecss.io/
https://bulma.io/

Arguably, we can also roll our own custom CSS as it probably isn't gonna be too complex to begin with for such a minimal site.

**Comment by tomsmeding** [comment]
Normally, and especially for something small like this, I'm always fairly strongly drawn towards doing it manually and not pulling in any unnecessary dependencies.

However, purecss actually looks pretty nice and very small. Let me have a brief look.

**Comment by tomsmeding** [comment]
Fine for now.
