### ISSUE TITLE
"Add another paste" interface for a single URL post

### ISSUE THREAD

**Issue by hyiltiz** [tomsmeding/pastebin-haskell#6]

**Comment by tomsmeding** [comment]
Do you mean that the paste view page should also include the interface from the homepage and allow you to submit a paste directly from there?

**Comment by hyiltiz** [comment]
I meant, in the home page, next to the "Submit" button, there can also be a button that says "Add another". Clicking it removes the original "Submit" and "Add another" buttons, inserts another insert box below, then adds those two buttons back. The home page remains until "Submit" is clicked. Once submitted, the paste view page should show *simultaneously* all of the pastes, maybe separated by
<hr>
 horizontal rules.
