### ISSUE TITLE
"Edit in a new paste" button on read page

### ISSUE THREAD

**Issue by tomsmeding** [tomsmeding/pastebin-haskell#9]
As suggested by [exa] at 2020-09-01T09:20:49Z

**Comment by hyiltiz** [comment]
Isn't that the same as "Make another paste" button? Or it is used to edit a currently pasted entry?

**Comment by tomsmeding** [comment]
This is specifically to copy the current paste into a paste creation window
to submit an updated one. Was suggested on IRC.

**Comment by hyiltiz** [comment]
Hmm, sounds useful as it is a common feature to use.
